-- 1. Tạo CSDL
CREATE DATABASE IF NOT EXISTS `erd_to_relational_db`
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE `erd_to_relational_db`;

-- 2. Tạo các bảng thực thể chính
CREATE TABLE IF NOT EXISTS `PHIEU_XUAT` (
    `SoPX` INT PRIMARY KEY AUTO_INCREMENT,
    `NgayXuat` DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS `VATTU` (
    `MaVT` INT PRIMARY KEY AUTO_INCREMENT,
    `TenVT` VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS `PHIEU_NHAP` (
    `SoPN` INT PRIMARY KEY AUTO_INCREMENT,
    `NgayNhap` DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS `NHA_CC` (
    `MaNCC` INT PRIMARY KEY AUTO_INCREMENT,
    `TenNCC` VARCHAR(150) NOT NULL,
    `DiaChi` VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `DON_DATHANG` (
    `SoDH` INT PRIMARY KEY AUTO_INCREMENT,
    `NgayDH` DATETIME NOT NULL,
    `MaNCC` INT NOT NULL,
    FOREIGN KEY (`MaNCC`) REFERENCES `NHA_CC`(`MaNCC`) ON DELETE RESTRICT
);

-- 3. Tạo các bảng trung gian (mối quan hệ n-m) và thuộc tính đa trị
CREATE TABLE IF NOT EXISTS `CHI_TIET_PHIEU_XUAT` (
    `SoPX` INT,
    `MaVT` INT,
    `DGXuat` DECIMAL(12, 2) NOT NULL,
    `SLXuat` INT NOT NULL CHECK (`SLXuat` > 0),
    PRIMARY KEY (`SoPX`, `MaVT`),
    FOREIGN KEY (`SoPX`) REFERENCES `PHIEU_XUAT`(`SoPX`) ON DELETE CASCADE,
    FOREIGN KEY (`MaVT`) REFERENCES `VATTU`(`MaVT`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `CHI_TIET_PHIEU_NHAP` (
    `SoPN` INT,
    `MaVT` INT,
    `DGNhap` DECIMAL(12, 2) NOT NULL,
    `SLNhap` INT NOT NULL CHECK (`SLNhap` > 0),
    PRIMARY KEY (`SoPN`, `MaVT`),
    FOREIGN KEY (`SoPN`) REFERENCES `PHIEU_NHAP`(`SoPN`) ON DELETE CASCADE,
    FOREIGN KEY (`MaVT`) REFERENCES `VATTU`(`MaVT`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `CHI_TIET_DON_DAT_HANG` (
    `SoDH` INT,
    `MaVT` INT,
    PRIMARY KEY (`SoDH`, `MaVT`),
    FOREIGN KEY (`SoDH`) REFERENCES `DON_DATHANG`(`SoDH`) ON DELETE CASCADE,
    FOREIGN KEY (`MaVT`) REFERENCES `VATTU`(`MaVT`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `NHACC_DIENTHOAI` (
    `MaNCC` INT,
    `SDT` VARCHAR(20),
    PRIMARY KEY (`MaNCC`, `SDT`),
    FOREIGN KEY (`MaNCC`) REFERENCES `NHA_CC`(`MaNCC`) ON DELETE CASCADE
);