CREATE DATABASE IF NOT EXISTS `quan_ly_don_hang`
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE `quan_ly_don_hang`;

CREATE TABLE IF NOT EXISTS `DON_VI_KH` (
    `MaDV` INT PRIMARY KEY AUTO_INCREMENT,
    `TenDV` VARCHAR(150) NOT NULL,
    `DiaChi` VARCHAR(255),
    `DienThoai` VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS `NGUOI_DAT` (
    `MaND` INT PRIMARY KEY AUTO_INCREMENT,
    `HoTenND` VARCHAR(100) NOT NULL,
    `MaDV` INT,
    FOREIGN KEY (`MaDV`) REFERENCES `DON_VI_KH`(`MaDV`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `NGUOI_NHAN` (
    `MaNN` INT PRIMARY KEY AUTO_INCREMENT,
    `HoTenNN` VARCHAR(100) NOT NULL,
    `MaDV` INT,
    FOREIGN KEY (`MaDV`) REFERENCES `DON_VI_KH`(`MaDV`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `NGUOI_GIAO` (
    `MaNG` INT PRIMARY KEY AUTO_INCREMENT,
    `HoTenNG` VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS `NOI_GIAO` (
    `MaDDG` INT PRIMARY KEY AUTO_INCREMENT,
    `TenNoiGiao` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `HANG` (
    `MaHang` INT PRIMARY KEY AUTO_INCREMENT,
    `TenHang` VARCHAR(150) NOT NULL,
    `DvTinh` VARCHAR(50),
    `MoTa` TEXT
);

-- 7. Tạo bảng Đơn Đặt Hàng & Chi Tiết Đơn Hàng
CREATE TABLE IF NOT EXISTS `DON_DAT_HANG` (
    `SoDH` INT PRIMARY KEY AUTO_INCREMENT,
    `NgayDat` DATE NOT NULL,
    `MaND` INT,
    FOREIGN KEY (`MaND`) REFERENCES `NGUOI_DAT`(`MaND`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `CHI_TIET_DON_HANG` (
    `SoDH` INT,
    `MaHang` INT,
    `SoLuong` INT NOT NULL CHECK (`SoLuong` > 0),
    PRIMARY KEY (`SoDH`, `MaHang`),
    FOREIGN KEY (`SoDH`) REFERENCES `DON_DAT_HANG`(`SoDH`) ON DELETE CASCADE,
    FOREIGN KEY (`MaHang`) REFERENCES `HANG`(`MaHang`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `PHIEU_GIAO_HANG` (
    `SoPG` INT PRIMARY KEY AUTO_INCREMENT,
    `NgayGiao` DATE NOT NULL,
    `SoDH` INT,
    `MaNN` INT,
    `MaNG` INT,
    `MaDDG` INT,
    FOREIGN KEY (`SoDH`) REFERENCES `DON_DAT_HANG`(`SoDH`) ON DELETE SET NULL,
    FOREIGN KEY (`MaNN`) REFERENCES `NGUOI_NHAN`(`MaNN`) ON DELETE SET NULL,
    FOREIGN KEY (`MaNG`) REFERENCES `NGUOI_GIAO`(`MaNG`) ON DELETE SET NULL,
    FOREIGN KEY (`MaDDG`) REFERENCES `NOI_GIAO`(`MaDDG`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `CHI_TIET_PHIEU_GIAO` (
    `SoPG` INT,
    `MaHang` INT,
    `SoLuong` INT NOT NULL CHECK (`SoLuong` > 0),
    `DonGia` DECIMAL(12, 2) NOT NULL,
    `ThanhTien` DECIMAL(15, 2) GENERATED ALWAYS AS (`SoLuong` * `DonGia`) STORED,
    PRIMARY KEY (`SoPG`, `MaHang`),
    FOREIGN KEY (`SoPG`) REFERENCES `PHIEU_GIAO_HANG`(`SoPG`) ON DELETE CASCADE,
    FOREIGN KEY (`MaHang`) REFERENCES `HANG`(`MaHang`) ON DELETE CASCADE
);